adminUser:
  password: vault:cjxd2/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: ldonley+github@cloudbees.com
  token: vault:cjxd2/pipelineUser:token
  username: ld-bot
prow:
  hmacToken: vault:cjxd2/prow:hmacToken
